# Generated by Django 4.2.6 on 2023-10-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="model_img",
            new_name="image",
        ),
    ]
