# Generated by Django 4.2.6 on 2023-10-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gs", "0002_rename_model_img_image_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="Img",
        ),
    ]
